version: '2.0'
services:

  db:
    container_name: db
    image: mysql:5.6
    volumes:
      - ./dbdata:/var/lib/mysql
    env_file:
      - env

  web:
    container_name: web
    build:
      context: .
      dockerfile: Magento_Dockerfile
    depends_on:
      - db
    ports:
      - "8080:80"
    links:
      - db
      - cache
      - recommender
    env_file:
      - env
    volumes:
      - ./app/pub:/var/www/html/pub

  adminer:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    env_file:
      - env
    restart: always
    ports:
    - 8888:80
    links:
      - db

  cache:
    image: redis
    container_name: redis
    ports: 
    - 6379:80

  varnish:
    build:
      context: ./varnish/
    container_name: varnish
    ports:
      - "80:80"
      - "6082:6082"
    links:
      - web

  recommender:
    build:
      context: ./tomcat/
    container_name: recommender
    #ports:
      #- "3000:8080"
    volumes:
      - "./tomcat/data:/usr/local/tomcat/data"

